// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roxmdmerzqzukmfeazua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJveG1kbWVyenF6dWttZmVhenVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjA4MzgsImV4cCI6MjA2NzM5NjgzOH0.sG2PvNovaCEJSBjCaAY-DQO_qn85B9A0wt6t2O8AvfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});